services:
  odoo:
    build: .
    container_name: odoo_app
    restart: always
    ports:
      - "8069:8069" # Port web Odoo
      # - "8072:8072" # Port untuk live chat/longpolling (opsional, aktifkan jika perlu)
    environment:
      - HOST=postgres
      - USER=user
      - PASSWORD=jsdbf762jfn2uf24492h4f
      - PORT=5432
      - ADMIN_PASSWORD=bolabot123 # Ganti ini!
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - app_network
    command: >
      odoo
      -d odoo_portfolio
      --no-database-list
      --db-filter=^odoo_portfolio$
      --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    security_opt:  # <-- TAMBAHKAN BLOK INI
      - apparmor:unconfined

volumes:
  odoo-data:

networks:
  app_network:
    external: true